### ISSUE TITLE
New issue request

### ISSUE THREAD

**Issue by bryanchen18** [Akash-Mittal/uber-invoice-maker#5]
Using the real fonts and Uber receipt images, can you make the final receipt more realistic to be used?

**Comment by Akash-Mittal** [comment]
Please provide the following.
1.) Sample Fonts.
2.) Example Image(More Realistic).
3.)  If possible please fork , make the changes and create pull request.

**Comment by bryanchen18** [comment]
Here is the template: https://codepen.io/mtthlbg/pen/RNOePb
You can also usek the report attached below
[ride_report_2019_05_09 (1).pdf](https://github.com/Akash-Mittal/uber-invoice-maker/files/3614411/ride_report_2019_05_09.1.pdf)
